from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import time
 
class TestPacientes:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.get('http://localhost:3000/auth/login')
        time.sleep(5)
    def teardown_method(self):
        self.driver.quit()
    print("prueba visual completada")
    def Test_Pacientes_Registro(self):
        self.driver.find_element(By.XPATH,"//input[@inputid='email1']").send_keys("chorizo@gmail.com")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@inputid='password1']").send_keys("qweQWE123")
        time.sleep(2)
        self.driver.find_element(By.XPATH, "//button[@class='p-button p-component w-full p-3 text-xl bg-orange-400']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='layout-menuitem-text']").send_keys("chorizo@gmail.com")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@id='nombres']").send_keys("potito")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@inputid='apellidos']").send_keys("feo")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//button[@class='p-datepicker-year p-link']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-datepicker-prev-icon pi pi-chevron-left']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-yearpicker-year'].text('2010')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-monthpicker-month'].text('Jan')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class=''].text('1')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-dropdown-label p-inputtext p-placeholder']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@aria-label='Masculino']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@id='telefono']").send_keys("69975312")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@id='ci']").send_keys("9249509")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@id='correo_electronico']").send_keys("caca@gmail.com")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-dropdown-label p-inputtext p-placeholder'].text('Seleccione una provincia')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@class='p-dropdown-item'].text('Abel Iturralde')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@id='zona']").send_keys("achocalla")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-button-label p-c'].text('Generar Usuario')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-button-label p-c'].text('Registrar paciente')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-button-icon p-c p-button-icon-left pi pi-refresh']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@type='search']").send_keys("Patricia")
        time.sleep(2)
        
        
    def Test_Pacientes_Actualizar(self):
        self.driver.find_element(By.XPATH,"//span[@class='layout-menuitem-text'].text('Actualizar pacientes')").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//div[@aria-label='Select 1']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//div[@aria-label = 'Seleccione un genero'']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@aria-label='Femenino']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-dropdown-label p-inputtext']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@aria-label='Larecaja']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//span[@class='p-button-label p-c']").click()
        time.sleep(2)
    def Test_Pacientes_Historia_Clinica(self):
        self.driver.find_element(By.XPATH,"//a[@href='/pacientes/historiaClinica']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@type='text']").send_keys("Eduardo")
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@class ='p-autocomplete-item']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//button[@aria-label= 'Crear historia medica']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//li[@class ='p-autocomplete-item']").click()
        time.sleep(2)
        
    
        